<?php
module_load_include('inc', 'drupal_nemlogin', 'includes/drupal_nemlogin');

/**
 * Implements hook_menu().
 */
function drupal_nemlogin_menu() {
  $items['nemlogin/require/%'] = array(
    'title' => t('Nemlogin require authentication'),
    'description' => t('Nemlogin require authentication'),
    'page callback' => 'drupal_nemlogin_require_auth',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/system/nemlogin'] = array(
    'title' => t('Configure Nemlogin'),
    'description' => t('Configure Nemlogin settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_nemlogin_menu_settings_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Generates settings page for nemlogin
 *
 * @return mixed
 */
function drupal_nemlogin_menu_settings_form() {
  $form = array();

  $form['drupal_nemlogin_simplesaml_installdir'] = array(
    '#type' => 'textfield',
    '#title' => t('Full path to simplesaml installation'),
    '#default_value' => variable_get('drupal_nemlogin_simplesaml_installdir'),
  );

  $form['drupal_nemlogin_simplesaml_default_auth'] = array(
    '#type' => 'textfield',
    '#title' => t('Simplesaml default auth method'),
    '#default_value' => variable_get('drupal_nemlogin_simplesaml_default_auth', 'default-sp'),
  );

  return system_settings_form($form);
}

/**
 * Page callback.
 * Creates SimpleSAML_Auth_Simple, sets up return to url and requires the authentification (actual redirect to IDP)
 *
 * @param $nid
 * @return string
 */
function drupal_nemlogin_require_auth($nid) {
  global $base_url;
  global $base_path;
  $return_to_link = $base_url . $base_path . "node/$nid";

  try {
    $as = getSimpleSamlAuth();
    $as->requireAuth(
      array(
        'ReturnTo' => $return_to_link
      )
    );
  } catch (Exception $e) {
    watchdog("Drupal nemlogin", t('Cannot initialize simplesaml request: ') . $e->getMessage(), array(), WATCHDOG_ERROR);
  }

  return '';
}

/**
 * Implements hook_form_alter().
 */
function drupal_nemlogin_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'webform_configure_form':

      $form['advanced']['drupal_nemlogin_link_enable_' . $form['nid']['#value']] = array(
        '#type' => 'checkbox',
        '#title' => t('Include nemlogin link'),
        '#default_value' => variable_get('drupal_nemlogin_link_enable_' . $form['nid']['#value'], 0),
      );
      $form['#submit'][] = 'drupal_nemlogin_webform_configure_save';
      break;

    case strstr($form_id, 'webform_client_form'):
      $nid = $form['#node']->nid;
      if (variable_get('drupal_nemlogin_link_enable_' . $nid, 0)) {
        try {
          $as = getSimpleSamlAuth();

          // Check if user is already authentificated.
          if ($as->isAuthenticated()) {
            // If CPR is fetched, prefill the form.
            $cpr = attemptFetchCpr($as);
            if ($cpr && variable_get('use_serviceplatform_to_get_address') && module_exists('vcv_serviceplatformen')) {
              $serviceplaformen_message = vcv_serviceplatformen_get_address($cpr);
              if ($serviceplaformen_message['status']) {
                $serviceplaformen_message['cpr'] = $cpr;

                drupal_nemid_populate_fields_recursive($form['submitted'], $serviceplaformen_message);
              }
            }

            // If CVR is fetched, prefill the form.
            $cvr = attemptFetchCvr($as);
            if ($cvr && variable_get('use_serviceplatform_to_get_address') && module_exists('vcv_serviceplatformen')) {
              $serviceplaformen_message = vcv_serviceplatformen_get_address($cpr);
              if ($serviceplaformen_message['status']) {
                drupal_nemid_populate_fields_recursive($form['submitted'], $serviceplaformen_message);
              }
            }

            global $base_url;
            global $base_path;
            $return_to_link = $base_url . $base_path . "node/$nid";

            // Logout url.
            $form['submitted'][] = array(
              '#markup' => '<a href="' . $as->getLogoutURL($return_to_link) . '">Logout af nemid</a>',
              '#weight' => -99,
            );
          }
          else {
            // If modify form to include the link for authentification.
            $form['submitted'][] = array(
              '#markup' => l('Login med Nemlogin', 'nemlogin/require/' . $nid),
              '#weight' => -99,
            );
          }
        } catch (Exception $e) {
          watchdog("Drupal nemlogin", t('Cannot initialize simplesaml request: ') . $e->getMessage(), array(), WATCHDOG_ERROR);
        }
      }

      break;
  }
}

/**
 * Save webform configuration
 */
function drupal_nemlogin_webform_configure_save($form, &$form_state) {
  $login_block_enable = $form_state['values']['drupal_nemlogin_link_enable_' . $form['nid']['#value']];
  variable_set('drupal_nemlogin_link_enable_' . $form['nid']['#value'], $login_block_enable);
}